### ISSUE TITLE
How does one install this module?

### ISSUE THREAD

**Issue by websterjazz** [0m4r/MMM-covid19#11]
I am a total newbie at coding ..I was successfully able to install many modules on magic mirror .. This one however I don't understand how to install... There is no link to get the installation file. Just config code . Can someone guide me how do I go about installing this module .

**Comment by 0m4r** [comment]
hi @websterjazz, thanks for your question and the interest in this magic mirror module.
At this link https://forum.magicmirror.builders/topic/4231/how-to-add-modules-for-absolute-beginners?_=1622723520331 you can find a very detailed step-by-step guide on how to install 3rd party modules (not just this one!)

Let me know if this helps you!
