### ISSUE TITLE
Defaults

### ISSUE THREAD

**Issue by maku1958** [0m4r/MMM-covid19#12]
Hello 0m4r,

I like to use your Module, but the defaults written in the MagicMirror config.js are not read by the executable files. Only the values in the node-helper.js are used. I have changed the values there and then they are loaded.
Can you fix this?

Maku

**Comment by 0m4r** [comment]
this is strange because I am pretty sure it works for me.
Could you add here your configuration?

**Comment by maku1958** [comment]
Hello Omar,
Thanx for replying:
Here is the text of my config.js with cleaned personal data-
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * see https://docs.magicmirror.builders/getting-started/configuration.html#general
 * and https://docs.magicmirror.builders/modules/configuration.html
 */
let config = {
	address: "localhost", 	// Address to listen on, can be:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/", 	// The URL path where MagicMirror is hosted. If you are using a Reverse proxy
					// you must set the sub path here. basePath must end with a /
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "ffff:192.168.178.45/24"], 	// Set [] to allow all IP addresses
															// or add a specific IPv4 of 192.168.1.5 :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
															// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "fr",
	locale: "fr-FR",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
	// local for armv6l processors, default
	//   starts serveronly and then starts chrome browser
	// false, default for all NON-armv6l devices
	// true, force serveronly mode, because you want to.. no UI on this device

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Férié",
			position: "top_left",
			config: {
				updateInterval: 3000,
				maximumEntries: 3,
				fadePoint: 0.25,
				calendars: [
					{
						symbol: "calendar-check",
						url: "https://calendar.google.com/calendar/ical/de.french%23holiday%40group.v.calendar.google.com/public/basic.ics",
					},
					
				]
			}
		},
		{
			 module: "calendar",
			 header: "k",
			 position: "top_left",
			 config: {
				updateInterval: 3000,
				maximumEntries: 5,
				fadePoint: 0.5,
				calendars: [
					{
						symbol: "calendar-check",
						url: "https://calendar.google.com/calendar/ical/xxx.basic.ics"
					},
				]
			}
		},
		{
			 module: "calendar",
			 header: "m",
			 position: "top_left",
			 config: {
				updateInterval: 3000,
				maximumEntries: 5,
				fadePoint: 0.5,
				calendars: [
					{
						symbol: "calendar-check",
						url: "https://calendar.google.com/calendar/ical/xxx/basic.ics"
					},
				]
			}
		},
		
		
		{
  disabled: false,
  module: "MMM-covid19",
  position: "bottom_right",
		defaults: {
			countryCodes: ['FR', 'DE', 'PO'],
			world: true,
			live: true,
			updateInterval: 24 * 60 * 60 * 1000,
			useScheduler: false,
			schedulerConfig: '0 0 */12 * * */1'
		},
},

		{
			module: "weather",
			position: "top_right",
			config: {
				weatherProvider: "openweathermap",
				type: "current",
				location: "xxx",
				locationID: "xxx", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city.
				apiKey: "xxx"
			}
		},
		{
			module: "weather",
			position: "top_right",
			header: "Meteo",
			config: {
				weatherProvider: "openweathermap",
				type: "forecast",
				location: "xxx",
				locationID: "xxx", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "xxx"
			}
		},
				{
			module: "MMM-MoonPhase",
			position: "top_right",
			config: {
				updateInterval: 43200000,
				hemisphere: "N",
				resolution: "detailed",
				basicColor: "white",
				title: true,
				phase: true,
				x: 100,
				y: 100,
				alpha: 0.7
			}
		},
		
		{
    module: 'MMM-WiFiPassword',
    position: "top_right",
      config: {
        //See 'Configuration options' for more information.
        header: "WiFi-Invité",
        network: "xxx", 
        password: "xxx",
      }
  },
  {
		disabled: false,
		module: 'MMM-OpenHAB-Items',
		position: "top_right",
		config: {
			url: "https://username:password@openhab.example/rest/items/",
			items: [
				{
					item_name: "TableLight",
					icon: "light",
					
				},
				{
					item_name: "Rolladen_Balkon",
				}
			],
                
		}	
	},
		{
			disabled: false,
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
					},
					
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by maku1958** [comment]
The inserted code does not look correct for me:
I try again:
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * see https://docs.magicmirror.builders/getting-started/configuration.html#general
 * and https://docs.magicmirror.builders/modules/configuration.html
 */
let config = {
	address: "localhost", 	// Address to listen on, can be:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/", 	// The URL path where MagicMirror is hosted. If you are using a Reverse proxy
					// you must set the sub path here. basePath must end with a /
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "ffff:192.168.178.45/24"], 	// Set [] to allow all IP addresses
															// or add a specific IPv4 of 192.168.1.5 :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
															// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "fr",
	locale: "fr-FR",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
	// local for armv6l processors, default
	//   starts serveronly and then starts chrome browser
	// false, default for all NON-armv6l devices
	// true, force serveronly mode, because you want to.. no UI on this device

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Férié",
			position: "top_left",
			config: {
				updateInterval: 3000,
				maximumEntries: 3,
				fadePoint: 0.25,
				calendars: [
					{
						symbol: "calendar-check",
						url: "https://calendar.google.com/calendar/ical/de.french%23holiday%40group.v.calendar.google.com/public/basic.ics",
					},
				]
			}
		},
		{
			 module: "calendar",
			 header: "k",
			 position: "top_left",
			 config: {
				updateInterval: 3000,
				maximumEntries: 5,
				fadePoint: 0.5,
				calendars: [
					{
						symbol: "calendar-check",
						url: "https://calendar.google.com/calendar/ical/xxx.basic.ics"
					},
				]
			}
		},
		{
			 module: "calendar",
			 header: "m",
			 position: "top_left",
			 config: {
				updateInterval: 3000,
				maximumEntries: 5,
				fadePoint: 0.5,
				calendars: [
					{
						symbol: "calendar-check",
						url: "https://calendar.google.com/calendar/ical/xxx/basic.ics"
					},
				]
			}
		},	
		{
  disabled: false,
  module: "MMM-covid19",
  position: "bottom_right",
		defaults: {
			countryCodes: ['FR', 'DE', 'PO'],
			world: true,
			live: true,
			updateInterval: 24 * 60 * 60 * 1000,
			useScheduler: false,
			schedulerConfig: '0 0 */12 * * */1'
		},
		},
		{
			module: "weather",
			position: "top_right",
			config: {
				weatherProvider: "openweathermap",
				type: "current",
				location: "xxx",
				locationID: "xxx", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city.
				apiKey: "xxx"
			}
		},
		{
			module: "weather",
			position: "top_right",
			header: "Meteo",
			config: {
				weatherProvider: "openweathermap",
				type: "forecast",
				location: "xxx",
				locationID: "xxx", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "xxx"
			}
		},
				{
			module: "MMM-MoonPhase",
			position: "top_right",
			config: {
				updateInterval: 43200000,
				hemisphere: "N",
				resolution: "detailed",
				basicColor: "white",
				title: true,
				phase: true,
				x: 100,
				y: 100,
				alpha: 0.7
			}
		},
		}		{
    module: 'MMM-WiFiPassword',
    position: "top_right",
      config: {
        //See 'Configuration options' for more information.
        header: "WiFi-Invité",
        network: "xxx", 
        password: "xxx",
      }
  },
  {
		disabled: false,
		module: 'MMM-OpenHAB-Items',
		position: "top_right",
		config: {
			url: "https://username:password@openhab.example/rest/items/",
			items: [
				{
					item_name: "TableLight",
					icon: "light",
					
				},
				{
					item_name: "Rolladen_Balkon",
				}
			],   
		}	
	},
		{
			disabled: false,
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
					},
					
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by 0m4r** [comment]
the way you configure the module is not correct, try this:
```js
{
  disabled: false,
  module: "MMM-covid19",
  position: "bottom_center",
  config: {
    updateInterval: 12 * 60 * 60 * 1000,
    countryCodes: ['FR', 'DE', 'PO'],
    world: true,
    live": true,
    updateInterval: 24 * 60 * 60 * 1000,
    useScheduler: false,
    schedulerConfig: '0 0 */12 * * */1' // thus is ignored as "useScheduler" is set to "false"
  }
}
```

**Comment by maku1958** [comment]
Thank you°
It works now. I have copied the original node-helper back in the module file and changed the defaults to config in the config.js.
