### ISSUE TITLE
Feature Request: Adding the worlds total statistics

### ISSUE THREAD

**Issue by xKrummy** [0m4r/MMM-covid19#3]
Adding world stats should be an easy but nice improvement. It could be added as a first entry in the table, if enabled in global configs. 

It should be turned on / off via a config flag, like 
- showWorldStats: <boolean>

I would wish for the possibility to show based on the global configs:
- see only world stats (if showWorldStats is true and no country provided)
- world and country stats (if showWorldStats is true and at least one country is provided)
- only country stats (if showWorldStats is false and the least one country is provided)

based on the api: https://documenter.getpostman.com/view/10808728/SzS8rjbc#e831c268-9da1-4d86-8b5a-8d7f61910af8 this can be done using a request like
`https://api.covid19api.com/world?from=2020-11-26T00:00:00Z&to=2020-11-27T00:00:00Z`

For the code i can give you already an sample on how to retrieve the correct timestamp from yesterday and from today for the request. Rest of the code in the following sample is based on your used structure.

```
var today = new Date();        
var yesterday = new Date()        
yesterday.setDate(today.getDate() - 1);  //if done base on <today> it could lead to a timestamp in milliseconds
//following returns a timestamp in the format of YYYY-MM-DDT00:00:00Z 
// This is needed for the request (sample: 2020-11-26T00:00:00Z). Be aware that January is 0 and therefore a getMonth() + 1 is used
var todayZuluTimestamp =  today.getFullYear() + "-" + String(today.getMonth() + 1).padStart(2, '0') + "-" + String(today.getDate()).padStart(2, '0') + "T00:00:00Z";
var yesterdayZuluTimestamp =  yesterday.getFullYear() + "-" + String(yesterday.getMonth() + 1).padStart(2, '0') + "-" + String(yesterday.getDate()).padStart(2, '0') + "T00:00:00Z";

var urlForReq = "https://api.covid19api.com/world?from=" + todayZuluTimestamp + "&to=" + yesterdayZuluTimestamp 

 const req = new Promise((resolve, reject) => request({
                url: `${urlForReq}`,
                method: 'GET'
            }, (error, response, body) => {
                if (!error && response.statusCode == 200) {
                    resolve(JSON.parse(body))
                }
                reject([])
                console.log(this.name, 'fetchLive request failed for', country)
            }));
            requests.push(req);
```

And thanks for the cool project! :)

**Comment by 0m4r** [comment]
Hi @xKrummy, I have added to the global numbers using the /summary endpoint as the /world one is marked as WIP and its response differs from the documented one.
You can pull the new code and see the changes. The configuration is added to the README.md file.
