### ISSUE TITLE
Headers and values are not alligned

### ISSUE THREAD

**Issue by xKrummy** [0m4r/MMM-covid19#4]
I have pulled the latest code and updated the config, but now the headers are not alligned with the numbers anymore.

Headers seems to be aligned to left side while the numbers are aligned to the right. looks a bit strange

![grafik](https://user-images.githubusercontent.com/63869212/101377162-c62ae980-38b1-11eb-9ce4-4d2cb84c2144.png)

**Comment by 0m4r** [comment]
Hi - this is fixed.
It was a tentative to align numbers to better read them. 
I found a different solution, the layout is much better now and the numbers more readable
