### ISSUE TITLE
World stats for "Active" returns no value, but only "New" as value

### ISSUE THREAD

**Issue by xKrummy** [0m4r/MMM-covid19#5]
World stats for "Active" returns no value, but only "New" as content
I would have expected here a value as well (for Recovered / Deaths /Confirmed it worked out fine)

![grafik](https://user-images.githubusercontent.com/63869212/101377278-e9559900-38b1-11eb-8eab-6ca635641047.png)

**Comment by 0m4r** [comment]
Hi - Thanks for reporting this.
Unfortunately it is not a bug as the values for the active numbers are not returned by the APIs.
So, I have added Total and New as label to avoid the empty cells.

**Comment by 0m4r** [comment]
hey @xKrummy I figured I could calculate those values by myself, and so I did!
You can update the code if you want and let me know! :)
