### ISSUE TITLE
HK doesn't work 

### ISSUE THREAD

**Issue by Brayds** [0m4r/MMM-covid19#6]
There is a bug with Hong Kong Country code  "HK"; stops the module from loading.

**Comment by 0m4r** [comment]
It looks like the API does not return data for HK, none of the API calls used in the module returns data for HK
- https://api.covid19api.com/total/country/HK
- https://api.covid19api.com/summary
of course, the module should not crash in this case.
I'll be looking into it, thanks for reporting it.

**Comment by 0m4r** [comment]
@Brayds I have released a new version of the module.
It should now not crash if an API call returns no results and the lack of data is also shown back in the module (see updated screenshot). I hope this works better for you!
