### ISSUE TITLE
County's don't work

### ISSUE THREAD

**Issue by Zuglagor** [0m4r/MMM-covid19#7]
The world will show numbers but country codes return nothing. Using default settings and country codes "US", "UK", "CA". Even default country codes dont work. Table shows whatever i type in for a country code

**Comment by 0m4r** [comment]
hi @Zuglagor unfortunately it is a data problem.
The APIs are returning values only until 7th Jan 2021.

You can try for any of the countries you mentioned above: https://api.covid19api.com/total/country/US 

The code I wrote tries to fetch this (from today - 2 to today -1)
https://api.covid19api.com/total/country/US?from=2021-01-07T00:00:00&to=2021-01-08T00:00:00
but it only returns data for today -2 so it does not get all the information to calculate the numbers to display.

Unfortunately, there is not much I can do about it.

**Comment by 0m4r** [comment]
@Zuglagor the APIs are now returning data so you should be able to see them in the module too.

**Comment by Zuglagor** [comment]
Cool. Thanks for clarifying. Kinda feel dumb for not noticing the dates when i was calling the api myself. Good module man. Thanks
