### ISSUE TITLE
module doesn't show country's information

### ISSUE THREAD

**Issue by ike-9** [0m4r/MMM-covid19#8]
I installed the module and tried exact same as sample configuration.
It only showed World numbers but countries.

Here is the output.

![image](https://user-images.githubusercontent.com/29009351/104267302-559e5c00-545f-11eb-9297-e8e89a133eb9.png)

**Comment by 0m4r** [comment]
hi @ike-9, thanks for reporting this!
I found the issue and fixed it with version 0.2.8.
Please note that there might be no data shown anyway as the API is not returning it.
You may get something like this:
![image](https://user-images.githubusercontent.com/451638/104283992-a63ea500-54b1-11eb-9ba4-e5358db080a9.png)

Do let me know if you have any further issue!

**Comment by ike-9** [comment]
Hello @0m4r , Thanks for your prompt action.

I tried country code "US" and it showed "-" for all columns just as Germany and Italy on your screenshot.
However, it seems like api returns something if I view that on my browser.

Is that expected results?

![image](https://user-images.githubusercontent.com/29009351/104343337-cf6b2f80-54c9-11eb-83fa-fb090f86dfae.png)

**Comment by 0m4r** [comment]
I do see data now:
![image](https://user-images.githubusercontent.com/451638/104344858-f6435900-54fd-11eb-9ebe-d2f218432a1c.png)

The numbers are about (today -1) and (today-2).
The totals are the absolute values of (today-1)
The differences are calculated as (today - 1) - (today - 2).

With a more concrete example, the numbers you see above are from this API call:
[https://api.covid19api.com/total/country/IT?from=2021-01-10T00:00:00&to=2021-01-11T00:00:00](https://api.covid19api.com/total/country/IT?from=2021-01-10T00:00:00&to=2021-01-11T00:00:00)
where:

- IT -> country (you can replace it with "US", for example)
- from -> today -2
- to ->  today -1

if the API from this call does not return valid data you get the "empty screen" as per your first screenshot.


Your API call in the example
https://api.covid19api.com/total/country/US?from=2021-01-11T00:00:00&to=2021-01-12T00:00:00

- from -> today -2
- to -> today

it is a different call than the one the module here does, but the response should be valid and display results anyway.
The point is that the /total endpoint does not give live data, for that, there is a specific one, but it is not very accurate and it does not cover live data for all countries, so I do not use it here.

I hope this makes sense, let me know if it is not clear.

**Comment by ike-9** [comment]
My configuration now is this:
![image](https://user-images.githubusercontent.com/29009351/104348268-8322ee00-54cf-11eb-9f11-77a619955268.png)

And it shows this:
![image](https://user-images.githubusercontent.com/29009351/104348308-9209a080-54cf-11eb-9253-5c2b91b94513.png)

Anything I'm missing?

**Comment by 0m4r** [comment]
I do get results with that configuration:
![image](https://user-images.githubusercontent.com/451638/104349571-63a5b880-5503-11eb-867a-22e883b3472f.png)

I know it is kind of a funny question, but, have you tried to restart it?
or can you see any error in the logs?

**Comment by ike-9** [comment]
Yes, I've tried restart it several times and there is no error on the logs.
Also, I've made sure that I can get data if I run curl command from the device.

Anything I can do for debugging?

**Comment by 0m4r** [comment]
I need to think about this. I have re-opened this bug report.
I am thinking it could be a "timezone" issue in calculating the dates.

Are you familiar with git?
Would you be able to checkout a test branch to help debug?

**Comment by ike-9** [comment]
Sure, I'm not expert of git, but I can do anything you need. Please let me know.

**Comment by 0m4r** [comment]
ok, so.... from the folder where you have cloned in this module can you run the following commands:
> git fetch -p

> git checkout bugfix/8

> git pull -r

and then restart MagicMirror?

if it still does not help, can you set the log to DEBUG by adding to the config.js this:
>logLevel: ["INFO", "LOG", "WARN", "ERROR", "DEBUG"]

**Comment by ike-9** [comment]
It worked!

![image](https://user-images.githubusercontent.com/29009351/104377203-1b32ce80-54f4-11eb-98e3-94352eb015ea.png)

Thank you so much.
Quick question, is there any plan that the module supports each state in the USA?

**Comment by 0m4r** [comment]
oh! that is great! I moved the changes into the main branch too.
You should switch back to it:

> git fetch -p
> git checkout main
> git pull -r

and restart.

About your other question, to be honest, I never looked into the API to see if showing data to a more granular level than the state is possible... I may want to do it and figure out if doable...

**Comment by ike-9** [comment]
I did switch back!
Thank you very much for your timely support!

And I noted yours regarding the answer.
